server:
  port: 2222
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: hello-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2222/eureka/



#配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true


